# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tommaso Capelli
email: tommaso.capelli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tommaso Capelli, 28, tech addicted. You can find my CV and my blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thetom88.github.io/ # the base hostname & protocol for your site
twitter_username: thetom88
github_username:  thetom88

# Build settings
markdown: kramdown
